version: '3.9'
services:
  ms_historia_academica: 
    # build: .
    image: dalvaradoc/ms_historia_academica
    ports:
      - 8080:8080
    depends_on:
      - db_historia_academica

  db_historia_academica:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

  
  